# Generated by Django 5.0.6 on 2024-07-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('beauty', 'Beauty'), ('books', 'Books'), ('toys', 'Toys'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
